name: fluxify
description: Social Discovery and Advertising Marketplace app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Navigation
  get: ^4.6.6
  
  # UI & Utilities
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  
  # Network & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  get_storage: ^2.0.3
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Authentication
  google_sign_in: ^6.2.1
  
  # Utilities
  intl: ^0.18.1
  logger: ^2.0.2+1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

